export {default as TermoIcon } from './TermoIxon' 

export { default as CarIcon } from './CarIcon'
export { default as CoolerIcon} from './Cooler'
export { default as DresserIcon } from './DresserIcon'
export { default as FenIcon } from './FenIcon'
export { default as HangerIcon } from './HangerIcon'
export { default as HotWater } from './HotWaterIcon'
export { default as KitchenIcon } from './KitchenIcon'
export { default as MashIcon } from './MashIcon'
export { default as MicroIcon } from './Microwave'
export { default as SpoonIcon } from './SpoonIcon'
export { default as TVIcon } from './TVIcon'
export { default as WashMachineIcon } from './WashMachine'
export { default as WhitenessIcon } from './WhitenesssIcon'
export { default as WifiIcon } from './WifiIcon'  